# "version" указывать необязательно. Если не указать, то будет использована актуальная версия.
# Планировалось зафиксировать версию для надёжности и воспроизводимости результата.
#version: "5.1"
# Но при работе возникало предупреждение, рекомендующее удалить версию, так как она игнорируется:
# the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"

services:
  # "app" будет использовано в качестве имени приложения/тега
  # При первом запуске для генерации новой базы можно использовать команду:
  # docker compose exec app python manage.py migrate
  # Опциональное создание первого пользователя-администратора:
  # 1. Узнать имя контейнера.
  # docker ps
  # В колонке "NAMES" будет имя контейнера. Например, "prod_app_1".
  # 2. Выполнить создание в интерактивном режиме
  # docker exec -it prod_app_1 python manage.py createsuperuser
  app:
    build:
      context: . # Кроссплатформенность. Для Linux требуется указать явно указать работу в текущем каталоге.
      dockerfile: ./Dockerfile
    command:
      # РАЗРАБОТКА:
#      # Альтернативно можно указать как в Dockerfile: ["python", "manage.py", "runserver"]
#      # Но разделением по строкам проще управлять (добавлять параметры), нет горизонтальной прокрутки.
#      - "python"
#      - "manage.py"
#      - "runserver"
#      # Текущая команда запустит сервер на стандартном порте - 8000. ip - 127.0.0.1.
#      # С внешней машины доступа не будет. Поэтому запускать надо на "0.0.0.0:8080". Порт выбран произвольно.
#      - "0.0.0.0:8080"
      # ПРОДУКТИВ:
      # Так как везде однозначно идентифицируются строки, можно писать без кавычек
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      # РАЗРАБОТКА:
#      # 8000 - порт хостовой машины (внешней машины).
#      # 8080 - порт контейнера.
#      - "8000:8080"
      # ПРОДУКТИВ:
      - "8000:8000"
    restart: always # Перезапуск при ошибках, перезагрузках и подобном
    # Настроить переменные окружения можно сразу здесь в отдельном блоке:
#    environment:
#      DJANGO_LOGLEVEL: INFO
    # Но с целью версионирования лучше вынести их в отдельный env-file. Пример файла в корне проекта - .env.template
    env_file:
      - .env
    logging:
      # ФАЙЛЫ JSON. Упрощённое логирование.
      driver: "json-file"
      options:
        # В сумме 2 Мб логов
        max-file: "10"
        max-size: "200k"
      # GRAFANA + LOKI. Отключено для упрощения. Требует запуск двух сервисов.
#      driver: loki # Имя драйвера из alias команды установки (см. ниже в сервисе "loki")
#      options:
#        # Так как драйвер работает снаружи сети Docker, можно указать localhost с портом, указанным в настройках:
#        # loki-url: http://localhost:3100/loki/api/v1/push
#        # Но правильнее будет использовать специальный адрес "host.docker.internal":
#        loki-url: http://host.docker.internal:3100/loki/api/v1/push
    volumes:
      - ./mysite/database:/app/database # Путь с каталогом "database" взять из "DATABASE_DIR" файла settings.py

# Логирование GRAFANA + LOKI. Отключено для упрощения. Требует запуск двух сервисов.
#  grafana:
#    # Указано с версией, а не "latest" для "заморозки зависимостей".
#    # Чтобы при выходе новой версии Grafana не поменялось поведение системы.
#    image: grafana/grafana:12.4.1
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true # Вход под "анонимным" пользователем - без пользователя и пароля
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # Назначение административных прав анонимному пользователю
#    ports:
#      - "3000:3000"
#
#  # Установка плагина-драйвера Docker "Loki Logging Driver" для подключения Loki к Grafana:
#  # docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
#  loki:
#    image: grafana/loki:3.6.7
#    ports:
#      - "3100:3100"