# Generated by Django 6.0.2 on 2026-03-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                default=1, # Миграции делались в одно время (в один "релиз"). Статей без категории быть не должно.
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.category",
            ),
            preserve_default=False,
        ),
    ]
