# Generated by Django 6.0.2 on 2026-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0006_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="blogapp.tag"
            ),
        ),
    ]
