# Generated by Django 6.0.2 on 2026-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0007_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True), # По аналогии с примером из видео курса
        ),
    ]
