"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from os import getenv
from pathlib import Path

from django.conf.global_settings import LOGGING
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from drf_spectacular.settings import SPECTACULAR_DEFAULTS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ДОБАВЛЕНО

# Параметры окружения для настройки из Docker.
# Префикс настроек 'DJANGO_' нужен для гарантии уникальности имён. Префикс выбран произвольным образом.
_ENV_PREFIX = 'DJANGO_'

# Отдельный каталог для базы данных для возможности настройки в Docker
DATABASE_DIR = BASE_DIR / 'database'
DATABASE_DIR.mkdir(exist_ok=True) # Создать в случае отсутствия


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# ДОБАВЛЕНО getenv для Docker
SECRET_KEY = getenv(
    f'{_ENV_PREFIX}SECRET_KEY', # 'DJANGO_SECRET_KEY'
    "django-insecure-1pv0tvc7o2xlln+em=t!9%dn_7n)6-)wpkovh272jqki@axulw"
)

# SECURITY WARNING: don't run with debug turned on in production!

# ДОБАВЛЕНО getenv для Docker. Ожидаются значения "1" или "0", так как из .env все значения читаются в виде строк.
DEBUG = getenv(f'{_ENV_PREFIX}DEBUG', '0') == '1'

ALLOWED_HOSTS = [
    '0.0.0.0', # Адрес прослушивания внутри контейнера Docker. Означает "слушать ото всюду". Извне по нему нет доступа.
    '127.0.0.1', # Адрес доступа к сервису в контейнере Docker с хостовой машины.
    # 'localhost', # Опционально для доступа в Windows через символьное имя.
] + getenv(f'{_ENV_PREFIX}ALLOWED_HOSTS', '').split(',') # ДОБАВЛЕНО для Docker. Адреса, разделённые запятой.

# ДОБАВЛЕНО для Django Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1', # При разработке без контейнера (без Docker)
]

# ДОБАВЛЕНО для Docker.
# ip может меняться, поэтому он определяется в процессе работы программы.
if DEBUG:
    import socket

    # Использование "__" вместо "_", так как "_" уже занят для локализации (алиас gettext)
    hostname, __, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS.append('10.0.2.2') # Внутренний адрес Docker. Он тут "может быть" (из курса).

    # Добавлять надо все адреса подсети.
    # Поэтому, например, "192.168.1.10" надо преобразовать в "192.168.1.1".
    INTERNAL_IPS.extend([ip[: ip.rfind('.')] + '.1' for ip in ips])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ДОБАВЛЕНО
    'django.contrib.admindocs', # Не по заданию. Документация в /admin.
    'django.contrib.sitemaps',
    
    'rest_framework',
    'django_filters',
    'drf_spectacular', # Генерация документации OpenAPI (Swagger)
    'debug_toolbar',

    'shopapp.apps.ShopappConfig',
    'requestdataapp.apps.RequestdataappConfig',
    'myauth.apps.MyauthConfig',
    'myapiapp.apps.MyapiappConfig', # Не из задания. Из курса.
    'blogapp.apps.BlogappConfig',
]

MIDDLEWARE = [
    # ДОБАВЛЕНО
    # Кэширование. Обязательно первым:
    # "django.middleware.cache.UpdateCacheMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    # ДОБАВЛЕНО
    # В задании требуется, но в курсе не показано. Место установки найдено самостоятельно.
    # Автоматически определяет язык в http-пути (/ru/, /en/ и т.д.)
    'django.middleware.locale.LocaleMiddleware',

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # ДОБАВЛЕНО
    # 'requestdataapp.middlewares.ThrottlingMiddleware', # Выключено за ненадобностью
    'django.contrib.admindocs.middleware.XViewMiddleware',  # Не по заданию. Документация в /admin. Использование bookmarklets.
    'debug_toolbar.middleware.DebugToolbarMiddleware',

    # Кэширование. Обязательно последним:
    # "django.middleware.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # Чтобы базовый шаблон был отдельно от приложений.
            # Путь прописывается от корня проекта. В текущем случае - от "верхнего" mysite.
            'templates'
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",

        # ДОБАВЛЕНО изменение хранение с BASE_DIR на DATABASE_DIR
        # "NAME": BASE_DIR / "db.sqlite3",
        "NAME": DATABASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# ДОБАВЛЕНО интернационализация и локализация (USE_L10N, LOCALE_PATHS, LANGUAGES)

USE_L10N = True

LOCALE_PATHS =[
    BASE_DIR / 'locale/'
]

# Использование перевода требует установку модуля gettext в ОС. На Windows без него ошибка выглядит примерно так:
# CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.19 or newer installed.
# Искать пришлось на сторонних ресурсах. Пример:
# https://mlocati.github.io/articles/gettext-iconv-windows.html
LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# ДОБАВЛЕНО (всё, что ниже)

# Не требуется локально при DEBUG=True.
# Дла выдачи статики в контейнере Docker или веб-сервером (ngnix).
# Предварительно надо вызвать команду подготовки статических файлов (можно указать в RUN Dockerfile).
# --noinput (или --no-input) - для автоматического подтверждения всех запросов без взаимодействия с пользователем.
# python manage.py collectstatic --noinput
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = '/media/'
MEDIA_ROOT = DATABASE_DIR / 'media_uploads' # В каталог базы данных, чтобы вынести файлы вне контейнера Docker
# DEFAULT_FILE_STORAGE = # Что является хранилищем (class-обработчик). В этой настройке можно указать облачное хранилище.

LOGIN_REDIRECT_URL = reverse_lazy('myauth:about-me') # Адрес перенаправления после успешной аутентификации
LOGIN_URL = reverse_lazy('myauth:login') # Путь при необходимости аутентификации. Например, при проверке прав.


# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [ # Настройка "по умолчанию". Может быть переопределена в "filter_backends" класса модели.
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # Документация OpenAPI
}

# drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'My Site project API',
    'DESCRIPTION': 'My site with shop app, custom auth, request app and middleware',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA' : False, # Не включать в документацию страницу, которая генерирует документацию (эту страницу)Регла
}

LOGLEVEL = getenv(f'{_ENV_PREFIX}LOGLEVEL', 'INFO').upper() # 'DJANGO_LOGLEVEL'. Обязательно в верхнем регистре.

# Вывод SQL-запросов в консоль. Использовалось для теста.
# LOGGING = {
#     'version': 1,
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'level': 'DEBUG',
#             'handlers': ['console'],
#         },
#     },
# }

# Логирование для Grafana Loki (и не только)
# Альтернативная передача настроек:
# logging.config.dictConfig({})
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Не отключать существующие логеры
    'formatters': {
        'verbose': { # Произвольное выбранное имя. Идентификатор для использования в настройках (см. ниже).
            'format': '%(asctime)s [%(levelname)s] %(name)s:%(lineno)s (%(module)s:%(funcName)s): %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOGLEVEL,
    },
    # Альтернативная запись "" корневого логера "root". Если переданы оба варианта, то приоритет у "root".
    # 'loggers': {
    #     '': {
    #         'level': LOGLEVEL,
    #         'handlers': ['console'],
    #     },
    # },
}

# Кэширование
# CACHES = {
#     "default": {
#         # Кэш в файлах. Хранение в каталоге "LOCATION".
#         # "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
#         # "LOCATION": "/var/tmp/django_cache",
#         # "LOCATION": "C:/django_cache", # Для Windows
#
#         # DummyCache - отключение кэширования
#         "BACKEND": "django.core.cache.backends.dummy.DummyCache",
#     }
# }

# Время кэширования, если подключены middleware в блоке "MIDDLEWARE"
# Если не менять, то будет знчение по умолчанию - 10 минут (600 секунд).
# CACHE_MIDDLEWARE_SECONDS = 200


