# Generated by Django 6.0.2 on 2026-02-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_rename_address_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "price"]},
        ),
    ]
